<a href="https://colab.research.google.com/github/CS-beep-dot/CS-beep-dot.github.io/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
from geopy.extra.rate_limiter import RateLimiter

In [10]:
df = pd.read_csv('RunnerData.csv')
df.head()

   Place    First     Last              City State  Age Division     Time
0      1   Daniel   Wilson             Tulsa    OK   35        M  8:23:01
1      2     Eric    Davis         Greenwood    IN   38        M  8:57:54
2      3  Stewart  Edwards  New Smyrna Beach    FL   43        M  9:24:35
3      4      Ron  Hammett         Montverde    FL   53        M  9:24:36
4      5     Seth     Cain            Geneva    FL   44        M  9:42:17

In [11]:
df2 = df.dropna(axis=1)

In [12]:
df2.head()

   Place    First     Last              City State  Age Division     Time
0      1   Daniel   Wilson             Tulsa    OK   35        M  8:23:01
1      2     Eric    Davis         Greenwood    IN   38        M  8:57:54
2      3  Stewart  Edwards  New Smyrna Beach    FL   43        M  9:24:35
3      4      Ron  Hammett         Montverde    FL   53        M  9:24:36
4      5     Seth     Cain            Geneva    FL   44        M  9:42:17

In [13]:
df2['fullname'] = df2['First'] + ' ' + df2['Last']

In [14]:
df2.head()

,Place,First,Last,City,State,Age,Division,Time,fullname
0,1,Daniel,Wilson,Tulsa,OK,35,M,8:23:01,Daniel Wilson
1,2,Eric,Davis,Greenwood,IN,38,M,8:57:54,Eric Davis
2,3,Stewart,Edwards,New Smyrna Beach,FL,43,M,9:24:35,Stewart Edwards
3,4,Ron,Hammett,Montverde,FL,53,M,9:24:36,Ron Hammett
4,5,Seth,Cain,Geneva,FL,44,M,9:42:17,Seth Cain

In [15]:
df2['Time'] = pd.to_timedelta(df2['Time'])
df2['Total_Minutes'] = df2['Time'].dt.total_seconds() / 60